### ISSUE TITLE
Humidity trigger

### ISSUE THREAD

**Issue by prj84** [balmli/no.almli.thermostat#1]
Hi! Would it be possible to make a humidity trigger as well? If humidity is over a given value, trigger a fan/switch.

Very usefull to bathroom, garages etc.

Today we have to use flows for this :-)

**Comment by balmli** [comment]
Hi.  Yes, That's a good idea.  I will add that

**Comment by prj84** [comment]
Perfect! :-) Thanks!
When will you add the app to apps.athom.com?

**Comment by balmli** [comment]
Hi.  It does not work with v. 2.0.0-rc.9.. due to a bug in the firmware, that Athom hopefully will fix in rc.10.

https://github.com/athombv/homey-apps-sdk-issues/issues/19

**Comment by prj84** [comment]
Tried now. The app just crashes when entering the device tile. I have reinstalled the app from beta branch and re added devices. still same thing. also on rc.12

**Comment by tooxe** [comment]
Works fine for me too (v.2.0.0-rc.12)
Thank you for a good work!

**Comment by prj84** [comment]
VThermostats work fine. VHumidity can be added, but crashes app when entering added device

**Comment by balmli** [comment]
Check the VHumidity device in v. 1.1.0
