### ISSUE TITLE
Danfoss Roomthermostat

### ISSUE THREAD

**Issue by Mindsuk** [balmli/no.almli.thermostat#10]
Hi!

Thank you for this great App! Is it possible to choose which temperature sensor i like to use for the zone? I‘ve got a Netatmo and a Danfoss Room Thermostat in our living room. But the virtual thermostat only use the Netatmo data! I would like the data of my Devolo Room Thermostat instead..

**Comment by balmli** [comment]
Hi,

No, it is not possible to select temperature sensor.  

The VThermo will calculate the average of all temperate sensors in the same zone.  

The Netatmo is a sensor, but the Danfoss Room Thermostat is not, even if it has temperature.
