### ISSUE TITLE
Danfoss LC-13

### ISSUE THREAD

**Issue by rindlerblabla** [balmli/no.almli.thermostat#11]
Maybe it's out of the scope of this issue tracker, but I am trying to use vthermo together with Danfoss LC-13 thermostats, which only has 'set a target temperature' as 'then', not just on/off. Could you give an idea to set this up? 

The Danfoss thermostat is situated near the window and therefore needs to be set a couple of degrees higher than the temperature sensor which works as the vthermo thermostat. Is it possible to use vthermo in this case?

**Comment by rindlerblabla** [comment]
Nevermind. Maybe it's just not necessary to use a virtual thermostat when there's I real one built in. Will see what settings on the LC-13 I have to set to get the temperature I want in the room. Think that's better usage of the batteries than to wake the thermostat up all the time to set a certain temperature.

**Comment by rindlerblabla** [comment]
Okey, hehe, reopening this issue to have your thoughts about it. Realize it would be better to set the value depending on sensors situated in a better place in the room than where the valve is. Any thought?

**Comment by balmli** [comment]
Hi.  The VThermo gets it's temperature as an average from all temperature sensors, and switches on / off sockets and virtual sockets based on the target temperature.  All these devices in the same zone.

I think you can use the VThermo as it is, by adding flows that updates the target temperature on the LC-13.

Flow 1: When: VThermo "Thermostat turned on" -> Then: LC-13 set target temperature 25 
Flow 2: When: VThermo "Thermostat turned off" -> Then: LC-13 set target temperature 15

or something like that.    The high temperature will then be the "on" state and the low temperature the "off" state.  You will have to find temperatures that suits you.
