### ISSUE TITLE
Not reading current temperature from Netatmo sensor correctly

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#12]
Hei Bjørnar.

I added a virtual thermostat to a room where I have a Netatom Weather Station device. The temperature in that room is currently 21.5, but the virtual thermostat says the current temperature is 9.7 for some reason. 

It seems the vThermo have a problem reading the temperature correctly from the Netatmo weather station. Is it possible for you to troubleshoot the problem?

**Comment by balmli** [comment]
Does the Netatmo have two temperatures?  One at 21.5 and another at -2.1 outside ?

So the average will be 9.7.

The VThermo calculates the average of all temperatures in the same zone.

**Comment by TheArcturian** [comment]
Yep, that was it. I moved away the outside temperature device from the room and now it works correctly.

It's nice to know the calculation information. I would recommend adding it to the notes of your app if it is not already there.

Thanks for your help!

**Comment by TheArcturian** [comment]
By the way, I have a pool where I use a Fibaro sensor to read the pool water temperature. I plan to add a motion sensor for the room as well which will include a temperature sensor for the air. That means I would have a need for two thermostats in this room. (The current thermostat turns on/off the water heater).

Also an average between those two sensors will be wrong. Any way to avoid that? It would be nice if we could which sensor the vThermo should read from in a future version in cases like this.

If not, I can create an extra room to separate them if it is not possible to code these features.

**Comment by balmli** [comment]
To keep the VThermo simple to use, I would prefer that you put it in a separate zone. 

And yes, I will update the readme-file with info about the average for temperature.
