### ISSUE TITLE
Feature request: Show current temperature on the device icon

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#13]
This is a feature request.

In the Homey app, your vThermo shows the **_selected_ temperature** in the squared icon. In the HomeKit app, the same icon shows the **_current_ temperature** instead. I find the latter more relevant as I usually want to know the temperature in the room. If I can see that just by looking at the device icon, it is a lot quicker and better in my view. 

What the room is set to is just something that goes on automatically in the background, but what the temperature actually is in the room is always relevant to know in a quick glance (without having to hold my finger for a few seconds on the device icon to see all the details).

Any chance you could change the information on the device icon from "temperature set" to "current temperature"?  Alternatively make it an option you can choose between in the settings or when you create the vThermo device?

**Comment by balmli** [comment]
This is the mobile app design by Athom, so it is not possible now.
But I hope it will be possible in the future.
