### ISSUE TITLE
Feature request: Turn On/Off the thermostat

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#14]
Hi again! :-)

I'm having many rooms that I only use some weekends or a few days through the month. In these rooms it would be great if I could turn off the thermostat exactly like it is done with your HeatingController by a single press on the device icon.

With that feature, I can easily turn on or off the thermostat when needed, and it will start heating from the temperature it was last set. Also if the thermostat is turned off, flows that I'm using will not do anything with the thermostats that is in an off state.

Is that a feature that is possible to implement? I would love to see that in a future version of your handy app.

**Comment by balmli** [comment]
Hi,

Not sure if there are bi-effects that might lead to errors for some of the users.

But I will look into it.

**Comment by TheArcturian** [comment]
Ok, thanks! Would be great to see this feature, making your app even more flexible and usable in more scenarios.

**Comment by balmli** [comment]
Sorry for the loooong delay on this issue.

I've just updated app store, and hopefully Athom will approve ... and you can start testing v. 1.1.5 ...

which will be a beta - versjon..

The v.1.1.5 should work with existing VThermo - devices, but to be able to use the on/off from the quick-action, the VThermo - device must be reinstalled.

**Comment by TheArcturian** [comment]
Sounds great! Thank you very much! I will test it as soon as I see Homey has updated it.

**Comment by balmli** [comment]
V 1.1.5 is in app store now, as beta.  Happy testing :-)

**Comment by TheArcturian** [comment]
Works great and exactly as hoped. Brilliant addition, Bjørnar! Takker så mye! :-)

**Comment by balmli** [comment]
Well, it was your idea..  I just changed the code. :-)


I close this issue now.
