### ISSUE TITLE
Qubino flush dimmer with temp sensor

### ISSUE THREAD

**Issue by peskareta** [balmli/no.almli.thermostat#15]
Hei!

I have a Qubino flush Dimmer with a temperature sensor connected.  The sensor in Homey shows 18,5deg C - but when having dimmer, heater anh vtherm in one sone - the vtherm will not read the current temperature from the qubino.

flush dimmer zmnhdd - with the supported temperature sensor.

VTherm displays "-" as current temperature.

Known problem - or impossible to read temperature from the qubino?

Thanks!  I will be using this to control my underfloor waterheating system (actuators)

**Comment by balmli** [comment]
Hi,

To be a thermometer for VThermo, the device must be a "sensor" and have a "measure_temperature"  capability.

You can check this if you access this link: https://developer.athom.com/tools/devices
and search for your thermometer.

**Comment by peskareta** [comment]
Hi!

The Qubino dimmer has the «measure_temperature» setting:

Am I doing something wrong?

Thank you for your reply!
I’m planning on using this as a temperature sensor for Heat-It Z-Water

Amund

**Comment by peskareta** [comment]
OK: Here I see the dimmer is a «light» type.
Is it somehow possible to work around this?

**Comment by peskareta** [comment]
Sorry for all the mails:
SOLVED: I installed a virtual app called «groups»
There they have I «sensor» device I could add - then Thermo could read it!

Great!
