### ISSUE TITLE
Vthermo doesn´t work after replacing plug-in switch

### ISSUE THREAD

**Issue by ketillund** [balmli/no.almli.thermostat#16]
I´ve been using Vthermo with a Fibaro motion sensor and a Telldus plug-in switch controlling an electric heater. This has been working flawlessly. 

However, a week ago I replaced the plug-in switch with a Telldus plug-in switch mini, in order to be able to measure the power consumption of the heater. I´ve made sure that the switch is assigned to the same room, and the old switch is renamed and moved to another room/zone. 
Since replacing the switch, Vthermo no longer turns the heater on and off, and it is constantly reporting a temperature of 20.8 degrees (which is wrong). 
The Fibaro motion sensor reports correct temperature, and the plug-in switch can be turned on and off manually (from the Homey-app).

**Comment by balmli** [comment]
Hi,

Can you search for the Fibaro motion sensor from https://developer.athom.com/tools/devices

And check that the sensor har class = 'sensor' ?
And that the measure_temperature capability is correct ?

**Comment by ketillund** [comment]
Yes, the motion sensor has class = ´sensor´

The measure_temperature capability is also correct:
measure_temperature | number | 20.9 |   | 9 minutes ago

**Comment by balmli** [comment]
Can you press the "Create diagnostics report" - button ?  And I will get a log.

And then try to reinstall the VThermo ?

**Comment by ketillund** [comment]
I´ve created a diagnostic report. Should I post the key here, or do you want it in a PM?

I´ve also deleted and reinstalled VThermo. So far, it only shows a ´-´for ´Current temperature´, so it doesn´t seem to be receiving the temperature from the motion sensor. And I´ve checked that the motion sensor has sent a temperature update after the VThermo app was installed and configured

**Comment by balmli** [comment]
Hi, 

Got the log..  This is the "session expired" bug in Homey..

Fixed in 2.1.2-rc.3
[Apps SDK] Fixed an issue that in some cases could cause apps to receive expired API tokens
https://firmware.athom.com/

You have to upgrade to 2.1.2-rc.3 or wait for the final 2.1.2 version

**Comment by ketillund** [comment]
It´s warm outside, so I´ll wait for 2.1.2 final :-) 
Thanks!

**Comment by balmli** [comment]
:-)
