### ISSUE TITLE
VThermo 1.1.5 Beta bugs

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#18]
A few bugs discovered today regarding the VThermo 1.1.5 beta:

1. Removed two old VThermo and added two VThermo yesterday. No problem. Everything was ok.
2. Removed a few ones today. Got a message about it wasn't able to delete it, but it was removed when I went back to the zone.
3. Added one new VThermo (v1.1.5). All okay. Added one more and then it appeared 6 times in the zone I had selected. Very strange.
4. Removed the 5 duplicates. All okay.
5. A few hours later I check the Homey app again and now the VThermo devices is unavailable: "Device is unavailable. The app may be disabled or the device cannot be connected to". It is for all my currently 8 VThermo devices.
Your app is still running so I choose to restart your app and everything is okay again.

All this might be related to the Homey app itself (latest current version installed), but I thought you should know anyways.

**Comment by balmli** [comment]
Are you on 2.2.0-rc.7 (or -5 or -6) ?

I've seen something like this, but on another app.

Can you press the "Create diagnostics report" - button ?

**Comment by balmli** [comment]
I think I have found a bug.. so I'll release 1.1.6 as alpha, that you can test.

If you want to alpha-test, can you send me your email that you use for Athom to bjornar.almli@gmail.com ?

**Comment by TheArcturian** [comment]
I'm running the official Homey App 2.3.2. I can accept to test betaversions, but I'm a bit dependent on stability so I'd like to stay clear of alpha versions.

**Comment by balmli** [comment]
OK. I'll release as beta, and then you can test.

**Comment by balmli** [comment]
V 1.1.7 is now released as beta. Please test.

**Comment by balmli** [comment]
Close this issue now.
