### ISSUE TITLE
Turn on/off through flow

### ISSUE THREAD

**Issue by rindlerblabla** [balmli/no.almli.thermostat#19]
Am trying to use forecast data to manage my heating. Have already defined what temperatures that should be set when the thermostat is on/off in other flows and it work just fine, but now I would like to turn the thermostat off if the cloud cover is low, but the only THEN-card that's available is Set temperature. Would it be possible to also have Turn thermostat on/off? Or have I missed something?

**Comment by balmli** [comment]
If you upgrade to v.1.1.7, which is a beta version, you can turn on / off with flows.

**Comment by rindlerblabla** [comment]
Have now updated to v.1.1.7. Still can't manage to turn on/off with flow, only set temperature. Am I doing something wrong?

**Comment by balmli** [comment]
You have to reinstall the VThermo in the zone.    Delete, then add.
