### ISSUE TITLE
Homey Appstore says my Homey sw is incompatible - I run 1.5.13

### ISSUE THREAD

**Issue by grenness** [balmli/no.almli.thermostat#2]
Don't know if this is the correct place to post this, let me know if I should delete!

![image](https://user-images.githubusercontent.com/9149572/50379230-6bf0d980-0644-11e9-8626-5a275dfdcec1.png)

![image](https://user-images.githubusercontent.com/9149572/50379238-a6f30d00-0644-11e9-84d4-1823ac02f672.png)

**Comment by balmli** [comment]
Yes, you need v. 2.0.0 for this app, since the app uses the "athom web api".

There is a bug in v. 2.0.0-rc.9, so it will not work in the latest version, but hopefully will this be fixed by Athom in the next release candidate, but that's another issue.
