### ISSUE TITLE
The problem with Apple Home and VThermo virtual thermostat

### ISSUE THREAD

**Issue by bulubash** [balmli/no.almli.thermostat#20]
Hello,

The virtual thermostat is easily added to the Apple Home program via plugin
https://apps.athom.com/app/com.swttt.homekit
and when you change the temperature in this thermostat with your Homey program, these changes immediately appear in the Home program, but when you change the temperature in the thermostat in the Home, these changes do not change the temperature in the thermostat in the Homey ( Homey sends the changes to the Home, but the Home does not transfer the changes to Homey). Sometimes, very rarely, all the same, Homey receives changes in the set temperature from the Home, but this happens once out of 10 and more often with upward changes, with downward changes, Homey does not receive data from the Home program.

Maybe this problem is not in your plugin, but in HomeyKit?

Thanks for the quick response.

**Comment by balmli** [comment]
The VThermo is a "thermostat" like other thermostats in Homey ..  So if other thermostat apps works, VThermo should work also.

Have you installed the latest version?  V. 1.1.10 ?  And then reinstalled the VThermo devices?  You'll have to rebuild your flows afterwards.
