### ISSUE TITLE
Timeout after Homey 2.5.2

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#23]
I get a timeout when clicking on vthermo devices after Homey was upgraded to 2.5.2. Netatmo also shutted down so I guess Athom broke something with its core fixes.

Restart of app or Homey does not help.

**Comment by balmli** [comment]
I see no such timeout myself, but will look into it.

**Comment by prj84** [comment]
I also have this since last update. I have tried to restart app and Homey but no luck :-( Both vThermo and vHumidity

**Comment by TheArcturian** [comment]
For some strange reason, it is working again now. I've done nothing since I tried last time and I tested it over many days.

So it can be closed if it is working for prj84 as well.

**Comment by prj84** [comment]
I still have the timeouts :-/

**Comment by balmli** [comment]
@prj84 Can to change the setpoint to low / high to force the VThermo to switch the sockets, and then press the "Create diagnostics report" - button i settings ?
I will get a report, and we might figure out what's wrong.   Might be some API change in Homey 2.5.2...

**Comment by prj84** [comment]
It is not possible to open devices. It just give a Time out. So it is not possible to change temperature.

Bug report from athom:
051a2f81-2681-4242-a66b-5fa16825440b

**Comment by balmli** [comment]
OK,  Can you delete the VThermo devices and reinstall ?   And see if that works ?

**Comment by prj84** [comment]
It’s not possible to add devices. Same Time Out. I’ll try to remove and add app.

**Comment by balmli** [comment]
Have you tried turning off the power and restarting the Homey ?

**Comment by prj84** [comment]
I removed the app and reinstalled all devices. I think this has to do with that I installed all devices with you initial version. Can ser that it has some new features now. Then you can close this :-)

**Comment by TheArcturian** [comment]
Good you were able to fix it too. :-)

**Comment by balmli** [comment]
Good to hear!

So this might affect users of the VThermo that have approved the Athom API a "long time ago"..

Not much else to do other than reinstall both the app and the devices..

**Comment by TheArcturian** [comment]
My problem came back after a reboot of Homey. I'm pretty sure it is Athom that screwed up this one with 2.5.2 as my Netatmo app ended up with the same "Timeout" error.

So I will remove all devices and reinstall the VThermo app to get it working again.

**Comment by balmli** [comment]
Try excluding and then including the wall plugs, or what your are controlling with the VThermo.  This has worked for other people.

**Comment by TheArcturian** [comment]
The Timeout error is back again for all Thermostats after a reboot of Homey.

The second reboot gave the same error, but after a while it was okay again.

However, after the third reboot all VThermos is again in a Timeout state and does not work. It has been like this for a day now. Any idea why this is happening?

All VThermo devices was earlier removed and added again with the newest version of Homey and VThermo.

**Comment by balmli** [comment]
Have you checked the state of the Z-wave devices ?

**Comment by TheArcturian** [comment]
Yes, the heating devices are working properly. And in developer > Z-Wave everything looks ok.

**Comment by balmli** [comment]
Yes, I realize there's something that fails for some users.   Trying to fix..

**Comment by TheArcturian** [comment]
Thanks! Just for your information, if I create a new thermostat, it works fine, but the existing ones still have the Timeout error.

**Comment by balmli** [comment]
Fixed in v. 1.1.13

**Comment by balmli** [comment]
See app store for v. 1.1.14.

**Comment by TheArcturian** [comment]
Seems fine now after a reboot of Homey.

**Comment by TheArcturian** [comment]
Just rebooted Homey after doing the antenna mod for Z-Wave and Zigbee. Everything works better and faster. However, the only thing not working at all after the reboot is HeatingController and VThermo. I get a Timeout again.

Restarting the two mentioned apps doesn't help. Deleting a VThermo device and recreating it works. However that is a hassle as they are based on flows.

Any advice?

**Comment by TheArcturian** [comment]
I removed all the VThermo devices, created them again and updated flows and Homekit devices to make it work again manually. After a new reboot of Homey, HeatingController works, but again, all the newly created VThermo devices does not work. Now the error when I click it is: 

"Something went wrong, please try again."

If I can be of any assistance in fixing the problem, please let me know. (And let me know if you still read this thread). Thanks.
