### ISSUE TITLE
Themostat doesn't react on heating

### ISSUE THREAD

**Issue by robiebab** [balmli/no.almli.thermostat#27]
Homey version: v2.5.2
VThermo App Version: v1.1.14
Nest V3 . Nest App V3.0.2

-vthermostat and the nest thermostat are in the same zone
scenario: when current temp = 18 and target temp = 22, heating be enabled in the VThermo app, except the actual heating doesn't start.

**Comment by balmli** [comment]
Hi,

The Nest app thermostat is a thermostat itself, and cannot be controlled from the VThermo app .. as it is now
