### ISSUE TITLE
I removed all the VThermo devices, created them again but still error

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#28]
I removed all the VThermo devices, created them again and updated flows and Homekit devices to make it work again manually. After a new reboot of Homey, HeatingController works, but again, all the newly created VThermo devices does not work. Now the error when I click it is: 

"Something went wrong, please try again."

When I try to configure the device, I can see the Timeout error.

If I can be of any assistance in fixing the problem, please let me know. (And let me know if you still read this thread). Thanks.

_Originally posted by @TheArcturian in https://github.com/balmli/no.almli.thermostat/issues/23#issuecomment-555465984_

**Comment by balmli** [comment]
Hi,

Sorry, I've been busy, but will find time to help.

How many VThermo + VHumidity devices do you have all together ?

**Comment by TheArcturian** [comment]
Thats fine. Thanks for getting back to me!

I have 6 VThermo and no VHumidity installed.

**Comment by balmli** [comment]
@TheArcturian 

New version for testing:

https://homey.app/no-no/app/no.almli.thermostat/VThermo/test/

**Comment by TheArcturian** [comment]
I think it went around a week and it started to work again by itself and it has been fine since. To me it seems like it might be Homey that does something strange in the startup of the Homey device. Or that the order of things in the boot varies and messes up your (and other) apps sometimes. I'm just guessing now, so I really dont know as the error is not stable.

It is however great that you focus on making sure it doesnt show up again on your part. As I havent seen the error since the end of november I really cant say if the new version helps though.

**Comment by balmli** [comment]
OK.  Close this issue now
