### ISSUE TITLE
Eurotronic spirit not detected as temperature sensor

### ISSUE THREAD

**Issue by Landerstraeten** [balmli/no.almli.thermostat#29]
I have a couple of Eurotronic spirit thermostatic valves at home. Each valve has a built-in temperature sensor. Unfortunately, VThermo is not detecting these temperatures.

Any idea how to fix this?

**Comment by balmli** [comment]
Yes, will support this in the next release

**Comment by balmli** [comment]
https://homey.app/a/no.almli.thermostat/test/
