### ISSUE TITLE
humidity query

### ISSUE THREAD

**Issue by AKTAKT** [balmli/no.almli.thermostat#31]
I love your app.  Just a question about the humidity setting though.  I have a Aeotec humidity sensor (Multisensor 6) how do I set this as the humidity to compare with?  I want to use your app to turn on a bathroom fan with a nano dimmer.

Thanks

Andy

**Comment by balmli** [comment]
The VHumidity device must be in the same zone as the Aeotec sensor.

Then you can create a flow with:

* When: VHumidity - humidity changes
* And: VHumidity - humidity has changed more than X % point last Y minutes
* Then: start fan

I use this myself, on my bathroom fan, with 3,5 % points in the last 2 minutes .. and the fan starts magically within 2-3 minutes after someone starts showering.  I also use a timer for the fan, so the fan will automatically stop after 30 minutes.

**Comment by AKTAKT** [comment]
That's great, thanks for the tips.  
Andy
