### ISSUE TITLE
Sonoff TH sensor

### ISSUE THREAD

**Issue by alezzand** [balmli/no.almli.thermostat#32]
@balmli
I installed your app in Homey, and it's promising to be very powerful for heating management!
My settings: I had some Sonoff (Tasmota) devices installed, all of them perfectly working with my flows.
But, after seeing what VThermo does, to simplify the temperature managing I created a test zone with a temperature sensor (Sonoff TH16), and a seperate switch (always Sonoff) with a heater plugged in. Then I installed VThermo and added to that zone a VThermo device.
Unfortunately VThermo doesn't work (or that is what seems to me): 
- opening the VThermo device and increasing/decreasing the temperature doesn't have any response from the switch; 
- the "Current temperature" doesn't show anything ("-");
- the "State" looks like the same ("-")

Maybe I did something wrong? 
I removed/reinstalled/restarted the app, but this didn't help...

**Comment by peskareta** [comment]
Try to add the “group” app. 
There you can fetch the temp sensor reading - and the vthermo will probably read the value. I need this for qubino temperature sensors.

**Comment by alezzand** [comment]
@peskareta You are super fast and fantastic! I almost racked my brains to find a solution...
Now it works perfectly: I'm using it with Homey Heating Scheduler, that is also a tremendous app!
Really many many thanks!!
