### ISSUE TITLE
In zones with 3 heat devices, VThermo is not able to turn on/off all of them

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#34]
I use VThermo in a room with 3 floor based water heat loops (vannbåren vannsløyfer). So I have 3 devices set as "Heater" devices in the same zone.

However, when VThermo turns on or off the heat in that room, only one or two of the devices is turned on or off. Usually just one of them.

It seems like Homey isn't able to process all three at the same time and just skips one or two of them. If you add a delay of 1-2 seconds on the Heater devices, I think it would be fine. Is there any chance you can debug or fix this issue?

If you need any more information, just let me know. The Heater devices is created with the Heatit Z-wave app.

**Comment by balmli** [comment]
Could add a setting for "delay" perhaps, between each device ?

**Comment by TheArcturian** [comment]
Yes, I think that would fix it. Anyways I guess it is Homey that is the main problem here. If you can create a workaround for it, it makes the days with Homey a little easier. ;-)

**Comment by gajdur** [comment]
Maybe as workaround: move the 3 heaters in subzone, make a virtual heater in the room zone and put it to flow "when virtual heater on then heater 1,2,3 on" and include delays?

**Comment by balmli** [comment]
I will add an advanced setting for a delay between switching..    so the user can choose..

Should really be handled by Homey (!) ... but what can you do... :-)

**Comment by TheArcturian** [comment]
Great, thank you very much!

Så sant, så sant... :-)

**Comment by balmli** [comment]
https://homey.app/a/no.almli.thermostat/test/

**Comment by TheArcturian** [comment]
The delay setting works perfect! The problem is solved.

Thank you very much again, Bjørnar!

**Comment by balmli** [comment]
Thanks for testing !
