### ISSUE TITLE
Possibility to start air condition when to hot

### ISSUE THREAD

**Issue by gajdur** [balmli/no.almli.thermostat#35]
Hi @balmli and thank you for the great App. I have a feature request and not a issue: is it possible to implement also air conditioner? Like now Heater on/off when cold/warm, but also with aircon on/off when to hot, when temperature for example 3 degrees over target? Thank you.

**Comment by balmli** [comment]
Yes, I think you can use the VThermo device.

You need a temp. sensor in the same zone as the VThermo device.

Go to advanced settings: check the "Invert switch".

Two flows:

1. when: VThermo - thermostat turned on, then: switch aircon on
2. when: VThermo - thermostat turned off, then: switch aircon off

**Comment by gajdur** [comment]
Thanks, going to try it.
