### ISSUE TITLE
Temperature is wrong when a fibaro door sensor without temp sensor in zone.

### ISSUE THREAD

**Issue by gajdur** [balmli/no.almli.thermostat#36]
Hi, i think the virtual thermostat is taking empty temperature sensors from my fibaro door sensor as value 0. For example if i have 2 temp sensors with 20 and 21 degrees and a door sensor with value "-" then is the zone temp into the thermostat 13.67 degrees.

**Comment by balmli** [comment]
VThermo calculates the temperature as an average of all temp sensors in the zone.

Just move the door sensor to another zone, and you'll be fine.

**Comment by gajdur** [comment]
Hi, only moving the sensor is not possible if i want to use the "thermostat off when window open". But i moved the sensor now to a separate zone and added a group device only with the door sensor and his contact capability. Going to test today if is working. Thanks.
