### ISSUE TITLE
Possibility to suspend vhumidity action

### ISSUE THREAD

**Issue by PaulSchryve** [balmli/no.almli.thermostat#37]
Hi,

I use the Vhumidity, but sometimes i need to force de-activation of the fan it commands.
(for bathroom, a shower will increase the humidity a lot, but i do not want to activate fan during the shower time)

For now the only option i have found is to force humidity threshold to 90%, but sometimes this doesn't work, as humidity >90%. 

My idea, is to allow de-activation of vhumidity, just like it is implemented on vthermo.
-> De-activation should stop fan(s) of the zone
-> using flows we can activate or de activate based on events.

Another option would be to allow a target of fan activation higher than 90%, 100% or more. 

Thanks for you tools ;-) Tell me if you need more details on the idea.

**Comment by balmli** [comment]
This will be fixed in v. 1.1.21

**Comment by PaulSchryve** [comment]
thanks
