### ISSUE TITLE
vthermo turning itself off several times a day

### ISSUE THREAD

**Issue by thomasekdahlN** [balmli/no.almli.thermostat#38]
I'm controlling the temperature in my floor (water heating) in entire house with actuators and sensors connected to Vthermo.

Vthermo worked great when I first set it up in desember 2019, but something has stopped working along the way. I suspect that the 4.1 update killed my vthermo?

Symptoms: All my instances of vthermo is turning itself off multiple times a day. And I have to check this manually at regular intervals to turn my heat on again. I'm getting a bit bored of this now and the house is always in a cold state since heating is turned off so often.

This is critical functionality for me, and if I cant solve this I have to throw Homey away and get another system.

Any logs I can find to see what turns vthermo off (I have made a feature request to Homey since the logging is so minimal that I'm not able to find out what actually turns off vthermo - I'm not sure it is vthermo itself, could be Homey, bugs making it stop, a flow, google assistant, tibber or a human beeing. I'm not able to find this out and it is a major weakness of Homey.

Is this a bug or a feature? How to solve it?

Bjørn - ser ut som du er norsk, så vi kan gjerne ringes eller ta et videomøte.

**Comment by balmli** [comment]
Hi Thomas,

What version of the app do you have?
Have you tried to reinstall the VThermo - devices ?

Yes, I'm norsk.  Kan kontaktes på Athom Homey Norge - facebook / Facebook.  No problem :-)

**Comment by thomasekdahlN** [comment]
I have version 1.1.20 (its automatically updated)

I have not tried to reinstall Vthermo devices, since that is a lot of work I have many of them;-) Is it necessary? 

Any secret logs I can find on what happens? Could it be the Vthermo device craching after an amount of time, it looks perfectly normal when I enable it after it was turned off.

Side note:
If reinstalling things helps and it stops working due to updates, I think I will turn off automatic updating. Can't have the house stop working at random times;-(

**Comment by balmli** [comment]
No, it shouldn't be necessary to reinstall.

**Comment by thomasekdahlN** [comment]
Any logs or debug info that I can retrieve for you?

**Comment by thomasekdahlN** [comment]
My Fibaro Wall Plugg has two options under setting for "Alltid på/Always on". This prevents Homey and other Apps from turning the unit off. Is it possible to implement this setting in Vthermo? It would solve my problem, even tough the Homey logging sucks.

Homeys logs are lacking so much needed info - that it is impossible to do any reasonable debugging.

![IMG_8733](https://user-images.githubusercontent.com/26059207/81645350-bc2f2e00-9429-11ea-9167-c5eb4561361c.PNG)
![IMG_8734](https://user-images.githubusercontent.com/26059207/81645365-bdf8f180-9429-11ea-832a-322c9bd5231c.PNG)
![IMG_8735](https://user-images.githubusercontent.com/26059207/81645368-bf2a1e80-9429-11ea-8ec0-27d2a7634f6b.PNG)

**Comment by thomasekdahlN** [comment]
Here is a id to a log from the vthermo App: 03f05787-419a-46c6-99d7-00e3374f06db

**Comment by thomasekdahlN** [comment]
Screen dump of on/off behaviour

![IMG_8744 3](https://user-images.githubusercontent.com/26059207/81807739-e9113d00-951e-11ea-9fed-7ff59386ef4d.PNG)

**Comment by thomasekdahlN** [comment]
I'm giving up on Homey now. The Homey ecosystem is too immature for me. Will find a more mature smarthouse system with working logs that tells me what actually triggers turning my units on and off.

**Comment by balmli** [comment]
Always on... is not supported by the VThermo.. 

So if the VThermo tries to control a Wall plug with "always on" it will fail.

**Comment by thomasekdahlN** [comment]
The wish was that Vthermo supported always on;-) 

The wallplug was just an example of the functionality I miss in Vthermo (since Vthermo turns off all the time)

**Comment by balmli** [comment]
I'm on Facebook / Messenger if you want to chat.

The Vthermo should not turn on / off like that..  It is controlled by the temperature in the zone..  

But, as I said, it does not work if the device is "always on"..  But that's not VThermo's fault.

**Comment by thomasekdahlN** [comment]
Its only my freeezer that is always on. because the first thing Homey did was to shut it off at night;-( The vthermo runs the Heatit Z-water relays (two pairs) and the relays works perfectly when run manually from the unit interface.

I'll send you a friend request on FB.

**Comment by balmli** [comment]
The VThermo can be switched off by other apps, e.g. Tibber integration, Google Home integration etc.

To avoid this, I will add a setting to disable switching the VThermo off.  

Wait for v. 1.1.21 in app store.
