### ISSUE TITLE
Virtual Thermostats shows wrong temperature

### ISSUE THREAD

**Issue by TheArcturian** [balmli/no.almli.thermostat#39]
The last couple of months the VThermo Thermostats often shows the wrong temperature. This has never been a problem before. When I restart the VThermo app in the homey app, it works correctly again.

Seems like it gets out of sync after a Homey reboot. Or something like that. Regardless, it is a very crucial bug as it stops turning the heating devices on or off correctly. I hope it can be fixed. If you need more info or a diag, just let me know.

**Comment by balmli** [comment]
Can you contact me on Slack (athomcommunity.slack.com), Homey Community https://community.athom.com/ or Facebook?

**Comment by TheArcturian** [comment]
Sure! What is your username in the forum or Facebook?

**Comment by balmli** [comment]
balmli / Bjørnar Almli

**Comment by dkvk** [comment]
Hi, did you work out any solution to this? I recently installed the app, after about one week temperature isn't updated. I need to restart the app to get it to update temperatures again.

**Comment by balmli** [comment]
Yes.

In v. 1.3.8, as an extra security every device is re-registered every 12 hours.

**Comment by dkvk** [comment]
Hmm.. seems to be some other issue for me then.

After the reboot of the app, the temperature started to show up correctly again. But the heater isn't triggered when needed.

I can control the heater from Homey stand-alone, so no issue with the power outlet I am using.

At this moment, as an example, the thermostat says it's heating to get to the target temperature. When I check the heater status screen it says the heater is in Idle state. The heater is not turned on.

Any idea?
