### ISSUE TITLE
Vthermo can't read temp from fibaro smart implant

### ISSUE THREAD

**Issue by Nick110893** [balmli/no.almli.thermostat#41]
Hi,

is there any reason why vthermo doesn't read the temp from fibaro smart implant sensors? is there a possibility to add this feature?

thanks in advance,

Nicky

**Comment by balmli** [comment]
Yes, the Fibaro smart implant doesn't have a separate "measure_temperature" capability. 

It has a lot of "measure_temperature.internal" + ".externalX" capabilities, but they are not supported by VThermo
