### ISSUE TITLE
Increase temperature of the thermostat to 120 degrees

### ISSUE THREAD

**Issue by Joostmo** [balmli/no.almli.thermostat#42]
Good evening,

Is possible to increase the maximum temperature of the thermostat to 120 degrees? We have a bio heater, which is connected to the central heating system. it works with this high temperatures.

Thank you in advance
I look forward to hearing from you.

**Comment by balmli** [comment]
Hi,

Yes, look for v. 1.5.1 which is in test now:

https://homey.app/a/no.almli.thermostat/test/

You can set the max temp in settings.

**Comment by Joostmo** [comment]
Good evening sir,

Thank you for the update, I tested it and it work perfectly. Thank you. 
Met vriendelijke groet, 

Joost Mol
