### ISSUE TITLE
Wrong temperature in second zone

### ISSUE THREAD

**Issue by tooxe** [balmli/no.almli.thermostat#5]
I discovered that one VThermo in one zone works fine  while adding the second VThermo into the second zone is stating wrong  temperature but only in the second zone.

**Comment by balmli** [comment]
Hi Tooxe,

Do you have several sensors in the second zone ? 

The temperature shown in the VThermo device in the mobile app is calculated as the average of all sensors with temperature capability in that zone.

Can you try to delete the second VThermo, and add it again ?

**Comment by tooxe** [comment]
I have tried by deleting VThermo, installing again and even by moving into different zones but the temperature still is not correct.
Unfortunately I can’t load up print screen here.

**Comment by balmli** [comment]
Can you contact me on Slack, you think ?   Bjørnar Almli on Athom community slack. https://slack.athom.com/

Or it should be possible to attach a picture here, by dragging and dropping to the comment area.

**Comment by tooxe** [comment]
Thank you but after the latest update everything seems to work.

**Comment by balmli** [comment]
That's good to heart
