### ISSUE TITLE
Does not recognize virtual heater?

### ISSUE THREAD

**Issue by bizzarooo** [balmli/no.almli.thermostat#8]
I have setup a virtual thermostat using Vthermo in the same zone as a virtual heater created via the Virtual Devices app. The thermostat collects the temperature from that zone, but does not manage to turn the virtual heater on or off. Do I have to do anything more?

**Comment by balmli** [comment]
V. 1.1.2 is in app store now

**Comment by bizzarooo** [comment]
Fantastic! It works. Thanks!

/Magnus
