### ISSUE TITLE
Humidity inversion

### ISSUE THREAD

**Issue by seegersnl** [balmli/no.almli.thermostat#9]
I cant invert the humidity, i have a very dry house so i want to increase the humidity thru a humidifier. Now i can only “decrese” the humidity. Second the slider doesnt shows a percentage, this makes it more of a gamble where to set it to. Besides these small problems it is a great app ;)

**Comment by balmli** [comment]
Hi.  Thanks for the feedback.  You are right, the VHumidity turns the fan off if the humidity is less than the target humidity, and then on if the humidity is larger than the target humidity.  So it does not work for a humidifier.  Adding a "invert" switch in Advanced settings for the device would fix this problem.  I will look into that for a new release.

And, also the dimmer UI in the mobile app is not very good for choosing the percentage for the humidity.  I tried using the thermostat UI, but that will only work for temperatures in the current version of the mobile app.  Using a flow to set the percentage for the humidity is possible.

**Comment by balmli** [comment]
New version 1.1.4 in app store now solves this issue.
